# Generated by Django 2.2.5 on 2019-09-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190922_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatars'),
        ),
    ]
