# Generated by Django 2.2.5 on 2019-09-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
