# Generated by Django 2.2.5 on 2019-09-25 21:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0008_auto_20190925_2149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('author', 'object_id', 'content_type')},
        ),
    ]
