# Generated by Django 2.2.5 on 2019-11-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190925_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
